# Generated by Django 4.0 on 2022-01-10 11:51

import Utilities.media_path_convertor
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cat_description', models.TextField(blank=True, max_length=100)),
                ('cat_image', models.ImageField(upload_to=Utilities.media_path_convertor.upload_category_image_path)),
                ('cat_active', models.BooleanField(default=True)),
                ('cat_created_date', models.DateTimeField(auto_now_add=True)),
                ('cat_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
