# Generated by Django 4.0 on 2022-01-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_alter_category_cat_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
