# Generated by Django 4.0 on 2022-01-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_rename_cat_slug_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
