# Generated by Django 4.0 on 2022-01-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
