# Generated by Django 4.0 on 2022-01-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_category_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='cat_active',
        ),
    ]
